services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug:3.141.59-vanadium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"

  node:
    image: node:16-alpine3.11
    environment:
      SELENIUM_SERVER_HOST: selenium
      SELENIUM_SERVER_PATH: /wd/hub
      USER: kuba
    depends_on:
      - selenium
    command: node index.js
    volumes:
      - .:/app
    working_dir: /app
